### ISSUE TITLE
FiniteHorizon not working

### ISSUE THREAD

**Issue by AlessandroSpallina** [AlessandroSpallina/Slicing-5G-MDP#1]
I have this error when i try to use fh with the new refactored code

```
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/SK3LA/PycharmProjects/Slicing-5G-MDP/src/slicing_core/main.py", line 76, in <module>
    main()
  File "C:/Users/SK3LA/PycharmProjects/Slicing-5G-MDP/src/slicing_core/main.py", line 47, in main
    policy.calculate_policy()
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\src\slicing_core\policy.py", line 252, in calculate_policy
    self._policy[i][j] = self._actions[self._policy[i][j]]
ValueError: setting an array element with a sequence.
````

**Comment by AlessandroSpallina** [comment]
done
