### ISSUE TITLE
vi float overflow

### ISSUE THREAD

**Issue by AlessandroSpallina** [AlessandroSpallina/Slicing-5G-MDP#5]
Process Process-6:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\src\slicing_core\policy.py", line 417, in _run_singleslice_from_confs
    p.calculate_policy()
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\src\slicing_core\policy.py", line 84, in calculate_policy
    self.obj.calculate_policy()
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\src\slicing_core\policy.py", line 116, in calculate_policy
    self._policy = list(self._run_value_iteration(self._config.discount_factor))
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\src\slicing_core\policy.py", line 297, in _run_value_iteration
    vi = mdptoolbox.mdp.ValueIteration(self._transition_matrix, self._reward_matrix, discount)
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\venv\lib\site-packages\mdptoolbox\mdp.py", line 1309, in __init__
    self._boundIter(epsilon)
  File "C:\Users\SK3LA\PycharmProjects\Slicing-5G-MDP\venv\lib\site-packages\mdptoolbox\mdp.py", line 1361, in _boundIter
    self.max_iter = int(_math.ceil(max_iter))
OverflowError: cannot convert float infinity to integer

**Comment by AlessandroSpallina** [comment]
fixed
